// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AckNotificationReducer from "../ack_notification_reducer";
import AdvanceAssignmentReducer from "../advance_assignment_reducer";
import ApplyIntakePatchReducer from "../apply_intake_patch_reducer";
import CompleteInboundWithoutPatchReducer from "../complete_inbound_without_patch_reducer";
import ConfirmDispatchAndAssignReducer from "../confirm_dispatch_and_assign_reducer";
import GrantRoleReducer from "../grant_role_reducer";
import RecordExtractionFailureReducer from "../record_extraction_failure_reducer";
import RecordInboundReducer from "../record_inbound_reducer";
import RecordSentQuestionReducer from "../record_sent_question_reducer";
import ResetDemoReducer from "../reset_demo_reducer";
import ResolveIncidentReducer from "../resolve_incident_reducer";
import RevokeRoleReducer from "../revoke_role_reducer";

export type AckNotificationParams = __Infer<typeof AckNotificationReducer>;
export type AdvanceAssignmentParams = __Infer<typeof AdvanceAssignmentReducer>;
export type ApplyIntakePatchParams = __Infer<typeof ApplyIntakePatchReducer>;
export type CompleteInboundWithoutPatchParams = __Infer<typeof CompleteInboundWithoutPatchReducer>;
export type ConfirmDispatchAndAssignParams = __Infer<typeof ConfirmDispatchAndAssignReducer>;
export type GrantRoleParams = __Infer<typeof GrantRoleReducer>;
export type RecordExtractionFailureParams = __Infer<typeof RecordExtractionFailureReducer>;
export type RecordInboundParams = __Infer<typeof RecordInboundReducer>;
export type RecordSentQuestionParams = __Infer<typeof RecordSentQuestionReducer>;
export type ResetDemoParams = __Infer<typeof ResetDemoReducer>;
export type ResolveIncidentParams = __Infer<typeof ResolveIncidentReducer>;
export type RevokeRoleParams = __Infer<typeof RevokeRoleReducer>;

