// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import AckNotificationReducer from "../ack_notification_reducer";
import AdvanceAssignmentReducer from "../advance_assignment_reducer";
import ApplyIntakePatchReducer from "../apply_intake_patch_reducer";
import CloseIncidentReducer from "../close_incident_reducer";
import CompleteInboundWithoutPatchReducer from "../complete_inbound_without_patch_reducer";
import ConfirmDispatchAndAssignReducer from "../confirm_dispatch_and_assign_reducer";
import GrantRoleReducer from "../grant_role_reducer";
import PrepareNotificationTranslationReducer from "../prepare_notification_translation_reducer";
import RecordExtractionFailureReducer from "../record_extraction_failure_reducer";
import RecordInboundReducer from "../record_inbound_reducer";
import RecordInboundTranslationReducer from "../record_inbound_translation_reducer";
import RecordSentQuestionReducer from "../record_sent_question_reducer";
import RecordSharedLocationReducer from "../record_shared_location_reducer";
import ReleaseConversationReducer from "../release_conversation_reducer";
import ResetDemoReducer from "../reset_demo_reducer";
import ResolveIncidentReducer from "../resolve_incident_reducer";
import RestartDemoReducer from "../restart_demo_reducer";
import RevokeRoleReducer from "../revoke_role_reducer";
import SendDispatcherMessageReducer from "../send_dispatcher_message_reducer";
import TakeOverConversationReducer from "../take_over_conversation_reducer";

export type AckNotificationParams = __Infer<typeof AckNotificationReducer>;
export type AdvanceAssignmentParams = __Infer<typeof AdvanceAssignmentReducer>;
export type ApplyIntakePatchParams = __Infer<typeof ApplyIntakePatchReducer>;
export type CloseIncidentParams = __Infer<typeof CloseIncidentReducer>;
export type CompleteInboundWithoutPatchParams = __Infer<typeof CompleteInboundWithoutPatchReducer>;
export type ConfirmDispatchAndAssignParams = __Infer<typeof ConfirmDispatchAndAssignReducer>;
export type GrantRoleParams = __Infer<typeof GrantRoleReducer>;
export type PrepareNotificationTranslationParams = __Infer<typeof PrepareNotificationTranslationReducer>;
export type RecordExtractionFailureParams = __Infer<typeof RecordExtractionFailureReducer>;
export type RecordInboundParams = __Infer<typeof RecordInboundReducer>;
export type RecordInboundTranslationParams = __Infer<typeof RecordInboundTranslationReducer>;
export type RecordSentQuestionParams = __Infer<typeof RecordSentQuestionReducer>;
export type RecordSharedLocationParams = __Infer<typeof RecordSharedLocationReducer>;
export type ReleaseConversationParams = __Infer<typeof ReleaseConversationReducer>;
export type ResetDemoParams = __Infer<typeof ResetDemoReducer>;
export type ResolveIncidentParams = __Infer<typeof ResolveIncidentReducer>;
export type RestartDemoParams = __Infer<typeof RestartDemoReducer>;
export type RevokeRoleParams = __Infer<typeof RevokeRoleReducer>;
export type SendDispatcherMessageParams = __Infer<typeof SendDispatcherMessageReducer>;
export type TakeOverConversationParams = __Infer<typeof TakeOverConversationReducer>;

