// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  conversationId: __t.u64().name("conversation_id"),
  messageId: __t.string().name("message_id"),
  text: __t.string(),
  receivedAt: __t.timestamp().name("received_at"),
  status: __t.string(),
  attempts: __t.u32(),
  lastError: __t.option(__t.string()).name("last_error"),
  caseEpoch: __t.u32().name("case_epoch"),
});
