// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  conversationKey: __t.string().name("conversation_key"),
  routePlatform: __t.string().name("route_platform"),
  routeSpaceId: __t.string().name("route_space_id"),
  routeLine: __t.option(__t.string()).name("route_line"),
  incidentId: __t.option(__t.u64()).name("incident_id"),
  assignmentId: __t.option(__t.u64()).name("assignment_id"),
  kind: __t.string(),
  text: __t.string(),
  callerLanguage: __t.string().name("caller_language"),
  translatedText: __t.option(__t.string()).name("translated_text"),
  translationLanguage: __t.option(__t.string()).name("translation_language"),
  eventAssignmentStatus: __t.option(__t.string()).name("event_assignment_status"),
  eventAt: __t.timestamp().name("event_at"),
  status: __t.string(),
  attempts: __t.u32(),
  lastError: __t.option(__t.string()).name("last_error"),
});
