// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  conversationKey: __t.string().name("conversation_key"),
  activeIncidentId: __t.option(__t.u64()).name("active_incident_id"),
  lastQuestion: __t.option(__t.string()).name("last_question"),
  lastQuestionDelivery: __t.option(__t.string()).name("last_question_delivery"),
  lastQuestionError: __t.option(__t.string()).name("last_question_error"),
});
