// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

import {
  FactChange,
  EvidenceInput,
} from "./types";

export default {
  conversationKey: __t.string(),
  expectedRevision: __t.u32(),
  sourceMessageIds: __t.array(__t.string()),
  intent: __t.string(),
  get changes() {
    return __t.array(FactChange);
  },
  summary: __t.string(),
  get evidence() {
    return __t.array(EvidenceInput);
  },
  corrections: __t.array(__t.string()),
  unresolvedFields: __t.array(__t.string()),
  recommendedServices: __t.array(__t.string()),
  recommendationRuleIds: __t.array(__t.string()),
  recommendationReason: __t.string(),
};
