// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";
import {
  CallerFacts,
  StoredEvidence,
} from "./types";


export default __t.row({
  id: __t.u64().primaryKey(),
  conversationId: __t.u64().name("conversation_id"),
  get facts() {
    return CallerFacts;
  },
  get evidence() {
    return __t.array(StoredEvidence);
  },
  summary: __t.string(),
  intakeRevision: __t.u32().name("intake_revision"),
  unresolvedFields: __t.array(__t.string()).name("unresolved_fields"),
  lastCorrections: __t.array(__t.string()).name("last_corrections"),
  recommendedServices: __t.array(__t.string()).name("recommended_services"),
  recommendationRuleIds: __t.array(__t.string()).name("recommendation_rule_ids"),
  recommendationReason: __t.string().name("recommendation_reason"),
  confirmedServices: __t.array(__t.string()).name("confirmed_services"),
  status: __t.string(),
  needsReview: __t.bool().name("needs_review"),
  extractionError: __t.option(__t.string()).name("extraction_error"),
  extractionState: __t.string().name("extraction_state"),
  caseEpoch: __t.u32().name("case_epoch"),
  createdAt: __t.timestamp().name("created_at"),
  updatedAt: __t.timestamp().name("updated_at"),
});
