// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  incidentId: __t.u64().name("incident_id"),
  kind: __t.string(),
  at: __t.timestamp(),
  unitId: __t.option(__t.string()).name("unit_id"),
  fields: __t.array(__t.string()),
  services: __t.array(__t.string()),
  detail: __t.option(__t.string()),
});
