// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

import {
  RouteInput,
} from "./types";

export default {
  provider: __t.string(),
  conversationKey: __t.string(),
  get route() {
    return RouteInput;
  },
  messageId: __t.string(),
  receivedAt: __t.timestamp(),
  latitude: __t.f64(),
  longitude: __t.f64(),
  accuracyMeters: __t.option(__t.f64()),
  label: __t.option(__t.string()),
  source: __t.string(),
};
