// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const AgentConversation = __t.object("AgentConversation", {});
export type AgentConversation = __Infer<typeof AgentConversation>;

export const AgentInbound = __t.object("AgentInbound", {});
export type AgentInbound = __Infer<typeof AgentInbound>;

export const AgentNotification = __t.object("AgentNotification", {});
export type AgentNotification = __Infer<typeof AgentNotification>;

export const Assignment = __t.object("Assignment", {
  id: __t.u64(),
  incidentId: __t.u64(),
  unitId: __t.string(),
  service: __t.string(),
  status: __t.string(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type Assignment = __Infer<typeof Assignment>;

export const AssignmentView = __t.object("AssignmentView", {});
export type AssignmentView = __Infer<typeof AssignmentView>;

export const CallerFacts = __t.object("CallerFacts", {
  incidentType: __t.option(__t.string()),
  locationText: __t.option(__t.string()),
  peopleInvolved: __t.option(__t.u32()),
  callerReportedConscious: __t.option(__t.bool()),
  callerReportedBreathing: __t.option(__t.bool()),
  fireOrSmoke: __t.option(__t.bool()),
  trappedPerson: __t.option(__t.bool()),
  violentThreat: __t.option(__t.bool()),
  injuryReported: __t.option(__t.bool()),
});
export type CallerFacts = __Infer<typeof CallerFacts>;

export const Conversation = __t.object("Conversation", {
  id: __t.u64(),
  conversationKey: __t.string(),
  activeIncidentId: __t.option(__t.u64()),
  lastQuestion: __t.option(__t.string()),
  lastQuestionDelivery: __t.option(__t.string()),
  lastQuestionError: __t.option(__t.string()),
  lastQuestionAt: __t.option(__t.timestamp()),
  caseEpoch: __t.u32(),
  routePlatform: __t.string(),
  routeSpaceId: __t.string(),
  routeLine: __t.option(__t.string()),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type Conversation = __Infer<typeof Conversation>;

export const ConversationContextRow = __t.object("ConversationContextRow", {
  id: __t.u64(),
  conversationKey: __t.string(),
  activeIncidentId: __t.option(__t.u64()),
  lastQuestion: __t.option(__t.string()),
  lastQuestionDelivery: __t.option(__t.string()),
  lastQuestionError: __t.option(__t.string()),
  caseEpoch: __t.u32(),
  routePlatform: __t.string(),
  routeSpaceId: __t.string(),
  routeLine: __t.option(__t.string()),
});
export type ConversationContextRow = __Infer<typeof ConversationContextRow>;

export const EvidenceInput = __t.object("EvidenceInput", {
  field: __t.string(),
  messageId: __t.string(),
  quote: __t.string(),
});
export type EvidenceInput = __Infer<typeof EvidenceInput>;

export const FactChange = __t.object("FactChange", {
  field: __t.string(),
  get value() {
    return FactValue;
  },
});
export type FactChange = __Infer<typeof FactChange>;

// The tagged union or sum type for the algebraic type `FactValue`.
export const FactValue = __t.enum("FactValue", {
  Unknown: __t.unit(),
  Bool: __t.bool(),
  Count: __t.u32(),
  Text: __t.string(),
});
export type FactValue = __Infer<typeof FactValue>;

export const InboundContextRow = __t.object("InboundContextRow", {
  id: __t.u64(),
  conversationId: __t.u64(),
  messageId: __t.string(),
  text: __t.string(),
  receivedAt: __t.timestamp(),
  status: __t.string(),
  attempts: __t.u32(),
  lastError: __t.option(__t.string()),
  caseEpoch: __t.u32(),
});
export type InboundContextRow = __Infer<typeof InboundContextRow>;

export const InboundInput = __t.object("InboundInput", {
  messageId: __t.string(),
  text: __t.string(),
  receivedAt: __t.timestamp(),
});
export type InboundInput = __Infer<typeof InboundInput>;

export const InboundMessage = __t.object("InboundMessage", {
  id: __t.u64(),
  dedupeKey: __t.string(),
  conversationId: __t.u64(),
  messageId: __t.string(),
  text: __t.string(),
  receivedAt: __t.timestamp(),
  status: __t.string(),
  attempts: __t.u32(),
  lastError: __t.option(__t.string()),
  appliedAt: __t.option(__t.timestamp()),
  caseEpoch: __t.u32(),
});
export type InboundMessage = __Infer<typeof InboundMessage>;

export const Incident = __t.object("Incident", {
  id: __t.u64(),
  conversationId: __t.u64(),
  get facts() {
    return CallerFacts;
  },
  get evidence() {
    return __t.array(StoredEvidence);
  },
  summary: __t.string(),
  intakeRevision: __t.u32(),
  unresolvedFields: __t.array(__t.string()),
  lastCorrections: __t.array(__t.string()),
  recommendedServices: __t.array(__t.string()),
  recommendationRuleIds: __t.array(__t.string()),
  recommendationReason: __t.string(),
  confirmedServices: __t.array(__t.string()),
  status: __t.string(),
  needsReview: __t.bool(),
  extractionError: __t.option(__t.string()),
  extractionState: __t.string(),
  caseEpoch: __t.u32(),
  createdAt: __t.timestamp(),
  updatedAt: __t.timestamp(),
});
export type Incident = __Infer<typeof Incident>;

export const IncidentView = __t.object("IncidentView", {});
export type IncidentView = __Infer<typeof IncidentView>;

export const MyRole = __t.object("MyRole", {});
export type MyRole = __Infer<typeof MyRole>;

export const Notification = __t.object("Notification", {
  id: __t.u64(),
  conversationId: __t.u64(),
  incidentId: __t.option(__t.u64()),
  assignmentId: __t.option(__t.u64()),
  kind: __t.string(),
  text: __t.string(),
  eventAssignmentStatus: __t.option(__t.string()),
  eventAt: __t.timestamp(),
  status: __t.string(),
  attempts: __t.u32(),
  lastError: __t.option(__t.string()),
  sentAt: __t.option(__t.timestamp()),
});
export type Notification = __Infer<typeof Notification>;

export const PendingNotificationRow = __t.object("PendingNotificationRow", {
  id: __t.u64(),
  conversationKey: __t.string(),
  routePlatform: __t.string(),
  routeSpaceId: __t.string(),
  routeLine: __t.option(__t.string()),
  incidentId: __t.option(__t.u64()),
  assignmentId: __t.option(__t.u64()),
  kind: __t.string(),
  text: __t.string(),
  eventAssignmentStatus: __t.option(__t.string()),
  eventAt: __t.timestamp(),
  status: __t.string(),
  attempts: __t.u32(),
  lastError: __t.option(__t.string()),
});
export type PendingNotificationRow = __Infer<typeof PendingNotificationRow>;

export const RoleGrant = __t.object("RoleGrant", {
  identity: __t.identity(),
  role: __t.string(),
  unitId: __t.option(__t.string()),
});
export type RoleGrant = __Infer<typeof RoleGrant>;

export const RoleInfo = __t.object("RoleInfo", {
  role: __t.string(),
  unitId: __t.option(__t.string()),
});
export type RoleInfo = __Infer<typeof RoleInfo>;

export const RouteInput = __t.object("RouteInput", {
  platform: __t.string(),
  spaceId: __t.string(),
  line: __t.option(__t.string()),
});
export type RouteInput = __Infer<typeof RouteInput>;

export const StoredEvidence = __t.object("StoredEvidence", {
  field: __t.string(),
  messageId: __t.string(),
  quote: __t.string(),
  intakeRevision: __t.u32(),
});
export type StoredEvidence = __Infer<typeof StoredEvidence>;

export const Unit = __t.object("Unit", {
  id: __t.string(),
  service: __t.string(),
  status: __t.string(),
});
export type Unit = __Infer<typeof Unit>;

export const UnitView = __t.object("UnitView", {});
export type UnitView = __Infer<typeof UnitView>;

